using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HoloHealthSystem.Domain.Enums
{
    public enum EEspecialty
    {
        podólogo,
        Acupuntura,
        AlergiaEImunologia,
        Anestesiologista,
        Angiologia,
        Cardiologia,
        CirurgiaCardiovascular,
        CirurgiaDeMão,
        CirurgiaDeCabeçaEPescoço,
        CirurgiaDoAparelhoDigestivo,
        CirurgiaGeral,
        CirurgiaOncológica,
        CirurgiaPediátrica,
        CirurgiaPlástica,
        CirurgiaTorácica,
        CirurgiaVascular,
        ClínicaMédica,
        Coloproctologia,
        Dermatologia,
        EndocrinologiaEMetabologia,
        Endoscopia,
        Gastroenterologia,
        GenéticaMédica,
        Geriatria,
        GinecologiaEObstetrícia,
        HematologiaEHemoterapia,
        Homeopatia,
        Infectologia,
        Mastologia,
        MedicinaDeEmergência,
        MedicinaDeFamíliaEComunidade,
        MedicinaDoTrabalho,
        MedicinaDeTráfego,
        MedicinaEsportiva,
        MedicinaFísicaEReabilitação,
        MedicinaIntensiva,
        MedicinaLegalEPeríciaMédica,
        MedicinaNuclear,
        MedicinaPreventivaESocial,
        Nefrologia,
        Neurocirurgia,
        Neurologia,
        Nutrologia,
        Oftalmologia,
        OncologiaClínica,
        OrtopediaETraumatologia,
        Otorrinolaringologia,
        Patologia,
        PatologiaClínicaOUMedicinaLaboratorial,
        Pediatria,
        Pneumologia,
        Psiquiatria,
        RadiologiaEDiagnósticoPorImagem,
        Radioterapia,
        Reumatologia,
        Urologia,
    }
}
